### ISSUE TITLE
Problem with a macro

### ISSUE THREAD

**Issue by wboeke** [Robert-van-Engelen/lisp#1]
Is there any reason why the following macro raises an error:
   (define ++ (macro (x) (list 'setq x (list '+ x 1))))
It is ment to act like the C function '++'. The error text is: unbound symbol. The symbol appears to be the '+

**Comment by Robert-van-Engelen** [comment]
Good first question! The reason is that `list` evaluates the arguments `'setq' then `x` and `(list '+ x 1))`. But this `x` is the problem, because `x` is first replaced by `n` then the `n` is evaluated by `list`. A macro constructs code, but the code is still evaluated in a way that may not be immediately intuitive. This is one of the reasons why Lisp implementations have so-called _quasiquotes_ to make this possible, but not easy (ugly) to look at IMHO. Maybe we should add quasiquotes?

**Comment by wboeke** [comment]
However ...
This macro works in other lisp 1's. E.g. in tiny-lisp the following is okay:
(setq ++ (macro (x) (list 'setq x (list '+ x 1))))
(setq r 4) (++ r)
Now r equals 5. Quasiquotes not needed, although it would be nice to have them.

**Comment by Robert-van-Engelen** [comment]
Should work now after the `setq` typo fix, see my EDIT.
