### ISSUE TITLE
Apply function?

### ISSUE THREAD

**Issue by wboeke** [Robert-van-Engelen/lisp#2]
An interesting way to specify a while loop is the following:

(define while (lambda (body . args)
  (apply body body args)))
(while (lambda (loop i)
         (if (not (eq? i 0))
             (begin
               (print i)
               (loop loop (- i 1)))
             'done)) 5)

It should print '54321done'. In your lisp implementation all needed functions are available, except 'apply'. Actually this function is used in a lot of other clever lisp examples, and it cannot be written as a macro. Do you think you can create it in your program?

**Comment by Robert-van-Engelen** [comment]
The `apply` is not needed, like the tinylisp project PDF explains. You just need to make sure a variable is used after the dot (because a literal list is concatted after the dot.) A few days ago I added an `apply` macro definition in examples/apply.lisp which expands as follows:

    (apply + 0 1 (list 2 3)) => (let* (_ (list 0 1 3 4)) (+ . _))

I don't know if there is a better way to define `apply` as a macro or perhaps as a primitive. I thing it's ugly though and appears to be just used by other Lisp that don't support the list dot in function arguments.

**Comment by wboeke** [comment]
Sorry, but this apply does'nt work.
For completeness I give a full example:
****************************************
(defmacro apply (f . args)
    (letrec*
        (c (lambda (t)
               (if (cdr t)
                   (cons (car t) (c (cdr t)))
                   (eval (car t)))))
        (list 'let* (list '_ (c (cons 'list args))) (cons f '_))))

(define while (lambda (body . args)
  (apply body body args)))

(while (lambda (loop i)
         (if (not (eq? i 0))
             (begin
               (print i)
               (loop loop (- i 1)))
             'done)) 5)
****************************************
When I run this, a looping outping is shown:
{2030}{2030}{2030}{2030}{2030}{2030}{2030} .....

I know how other lisp's implement 'apply', and I think it is not possible to do this in lisp itself. These lisp's support the dot operator as well.
Btw: your solution is okay for simple examples, e.g. (apply * '(2 3)) yields 6.

Kind regards,
Wouter Boeke

**Comment by Robert-van-Engelen** [comment]
Interesting. Sure, like I said I this is one possible way to create an `apply` macro, since I haven't seen any and there is surely a better macro to implement than this one. But my comment wasn't about the `apply` special form. Most Lisp implementations do not allow passing arguments with the dot operator, i.e. `apply` is a decent substitute that can be handy when the last argument as a list is a function call (the dot operator won't work without a `let` or `lambda` binding for the trailing list of arguments). The last `apply` argument is essentially a dot list in disguise.

Let me show that defining your `while` with a dot works fine as expected (but for sure, the `apply` macro still needs some work):

    (define while (lambda (body . args) (body body . args)))

    (while (lambda (loop i)
      (if (not (eq? i 0))
        (begin
          (print i)
          (loop loop (- i 1)))
        'done)) 5)

    54321done

Do you have any counter examples?

Note that there are cases when a `let` form is needed with the dot. Basically, I want the `apply` macro to create this version for your `while`:

    (define while
        (lambda (body . args)
            (let*
                (rest args)
                (body body . rest))))

such that only the last `args` are captured as `rest` with a `let`. Here the `let` is redundant of course. But in other cases it is needed, for example:

    (apply + 1 2 (list 3 4))

which becomes

    (let* (_ (list 3 4)) (+ 1 2 . _))

**Comment by Robert-van-Engelen** [comment]
Oh, and please note that the `let` forms are syntactically different than other Lisp that require a list. This is easy to change in the lisp.c code when desired for compatibility. My observation when teaching a programming design course in which I used MIT Scheme was that Scheme's `let` confused a lot of students. See the tinylisp PDF footnote.

**Comment by Robert-van-Engelen** [comment]
Here you go, I fixed the `apply` macro for you:

~~~
(defmacro apply fargs
    (letrec*
        (del (lambda (t)
            (if (cdr t)
                (del (cdr t))
                t)))
        (add (lambda (t s)
            (if (cdr t)
                (cons (car t) (add (cdr t) s))
                s)))
        (list 'let* (cons '_ (del fargs)) (add fargs '_))))
~~~
Works for the examples I've tested. But may need more thorough testing!! And perhaps tweaking...

PS. I use `let*` and `letrec*` because these are slightly more efficient than `let` and `letrec` in the C code.

**Comment by wboeke** [comment]
Your solution without apply works for this lisp, not for a regular scheme like chibi or guile. That's no problem for me, if an apply is not needed, I don't need a difficult macro to be able to use it.
Paraphrasing an old saying about another language: if you have seen one lisp you have seen one lisp. Lisp is a high-level language, so an implementer needs to make choices, resulting in many small differences.
You talk about apply as superfluous, but then one could say that all let's are superfluous also, if you have a define with local scope. The define in your lisp has always global scope, which makes it unusable within function bodies. Scheme's define is okay, Common Lisp's setq is a hybrid: it has local or global scope. Not very nice.

**Comment by Robert-van-Engelen** [comment]
> Your solution without apply works for this lisp

... which is (truly) based on McCarthy's original ideas that make this an _inherent_ property of this Lisp, I should add.

> Paraphrasing an old saying about another language: if you have seen one lisp you have seen one lisp. Lisp is a high-level language, so an implementer needs to make choices, resulting in many small differences.

The problem is that (byte-code) optimized Lisp machines don't automatically inherit this nice property. An `apply` is a necessary alternative, which is fine. But `apply` is _NOT_ required with a Lisp that (correctly) supports the dot, which makes Lisp _beautifully minimalistic_ when it does.

> You talk about apply as superfluous, but then one could say that all let's are superfluous also

Yes, they are both superfluous. The fundamental primitives of Lisp don't include `let`. Likewise, `apply` isn't included either in this Lisp and McCarthy didn't appear to require it either. Both `let` and `apply` can be macros built on top of existing Lisp functions. But `let` is quite common to use and it is _MUCH_ more efficient as a built-in primitive than a macro that constructs a closure with bindings to apply. Hence, `let` should be a primitive. But `apply` is no more optimal as a primitive than the dot. They're pretty much the same thing.

Lisp is a very malleable programming language, for good or bad. As long as there are no technical limits imposed by the Lisp engine, then all is good.

> The define in your lisp has always global scope, which makes it unusable within function bodies

I know. Use `let` or change the `define` implementation in ways you want. A `define` is a global definition that supports mutual recursion and can reference forward defines in its body as it always reference the latest defines in its body, as the PDF states. The intent of tinylisp and this project is to keep things simple and small, to offer a playground for experimentation to change and try things out.

**Comment by Robert-van-Engelen** [comment]
I've fixed an issue that affected the dot in an arguments list, which unfortunately popped up after optimizing the evaluator a couple of days ago.

My latest project implements a similar Lisp as this one, but with Cheney's garbage collection: https://github.com/Robert-van-Engelen/lisp-cheney

That new project was "fun" to implement, because it's far more challenging to manage the state of the machine when everything moves on the heap at any time by the GC. Therefore, testing is just as critical if not more so which I've done with several scripts like for this project.
