### ISSUE TITLE
Unexpected behavior of cond

### ISSUE THREAD

**Issue by rsimmons** [Robert-van-Engelen/lisp#4]
`(cond (() 42))` errors with  `ERR 1 not a pair`, whereas I would expect it to evaluate to `()`.

`(if () 42)` evaluates to `()`, as I would expect.

I'm not sure if this is a bug in `cond` or if I'm misunderstanding how it's supposed to work.

**Comment by genivia-inc** [comment]
Thanks for the feedback. The `cond` special form doesn't have a default when all conditions fail. Lisp isn't really standardized, so its up to the implementor to decide.

As you can see, the loop runs until a condition is not () or if the remaining list is (). If the remaining list `t = ()` then `f_begin(cdr(car(t)), e)` fails because `t = ()`.
~~~
L f_cond(L t, L *e) {
  while (T(t) != NIL && not(eval(car(car(t)), *e)))
    t = cdr(t);
  return f_begin(cdr(car(t)), e);
}
~~~
If you want `cond` to return () if no condition succeeds, then change this to
~~~
return T(t) != NIL ? f_begin(cdr(car(t)), e) : nil;
~~~

**Comment by genivia-inc** [comment]
Perhaps this is worth an update.

**Comment by Robert-van-Engelen** [comment]
Fixed.

**Comment by rsimmons** [comment]
Makes sense, thank you!
